# Generated by Django 4.1.4 on 2023-02-21 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_menu_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guest_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="last_name",
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default=datetime.date(2023, 2, 21)),
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(default=10),
        ),
    ]
