# Generated by Django 4.2.4 on 2023-09-01 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0004_remove_booking_comment_remove_booking_guest_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default=datetime.date(2023, 9, 1)),
        ),
    ]
